import { parse as parseYaml } from 'yaml';

export type RunMode = 'semi-auto' | 'full-auto';

export interface JenkinsJobConfig {
  jobName: string;
  branchParam?: string;
  envParam?: string;
  defaultParams?: Record<string, string>;
}

export interface GlabConfig {
  gitlab: { host: string; projectId: string; harnessClone?: string };
  workspace: { root: string };
  branchNaming: { format: string; typeMap: Record<string, string> };
  runMode: RunMode;
  deployBranch?: string;
  /** 角色 → 默认 @用户，Issue 无交付协同表时兜底，减少反复反问 */
  roles?: Record<string, string>;
  /** 单 job（jobName）或多仓 job 映射（jobs），二者可共存 */
  jenkins?: {
    jobName?: string;
    branchParam: string;
    defaultParams: Record<string, string>;
    jobs?: Record<string, JenkinsJobConfig>;
  };
  databases?: Record<string, { mcp: string; desc?: string }>;
  testEnvironments?: Record<string, { url: string; account?: string; password?: string; desc?: string }>;
}

interface RawJenkinsJob {
  job_name?: string;
  branch_param?: string;
  env_param?: string;
  default_params?: Record<string, string>;
}

interface RawConfig {
  gitlab?: { host?: string; project_id?: string; project_path?: string; harness_clone?: string };
  workspace?: { root?: string };
  branch_naming?: { format?: string; type_map?: Record<string, string> };
  run_mode?: string;
  deploy_branch?: string;
  roles?: Record<string, unknown>;
  jenkins?: { job_name?: string; branch_param?: string; default_params?: Record<string, string>; jobs?: Record<string, RawJenkinsJob> };
  databases?: Record<string, { mcp?: string; desc?: string }>;
  test_environments?: Record<string, { url?: string; account?: string; password?: string; desc?: string }>;
}

// Matches a ```yaml\n...\n``` fenced block exactly (no CRLF / trailing-space / uppercase support).
// Input is tool-generated by `/init-glab-flow` or copied from `config.example.md`, so this is acceptable.
function extractYamlBlock(markdown: string): string | null {
  const match = markdown.match(/```yaml\n([\s\S]*?)\n```/);
  const block = match?.[1];
  return block ?? null;
}

export function parseConfig(markdown: string): GlabConfig {
  const block = extractYamlBlock(markdown);
  if (block === null) throw new Error('config: no ```yaml fenced block found in config markdown');

  const parsed = parseYaml(block);
  if (!parsed || typeof parsed !== 'object' || Array.isArray(parsed)) {
    throw new Error('config: yaml block is empty or did not parse to an object');
  }
  const raw = parsed as RawConfig;

  const host = raw.gitlab?.host;
  const projectId = raw.gitlab?.project_id ?? raw.gitlab?.project_path;
  const root = raw.workspace?.root;
  if (!host || !projectId || !root) {
    throw new Error(
      `config: missing required fields — need gitlab.host, gitlab.project_id (or project_path), workspace.root; ` +
        `got host=${host ?? '<empty>'}, projectId=${projectId ?? '<empty>'}, root=${root ?? '<empty>'}`,
    );
  }

  const runMode: RunMode = raw.run_mode?.trim().toLowerCase() === 'full-auto' ? 'full-auto' : 'semi-auto';

  return {
    gitlab: {
      host,
      projectId: String(projectId),
      ...(raw.gitlab?.harness_clone ? { harnessClone: raw.gitlab.harness_clone } : {}),
    },
    workspace: { root },
    branchNaming: {
      format: raw.branch_naming?.format ?? '{type}/{iid}',
      typeMap: raw.branch_naming?.type_map ?? { story: 'feat', bug: 'fix' },
    },
    runMode,
    ...(raw.deploy_branch ? { deployBranch: raw.deploy_branch } : {}),
    ...(raw.roles
      ? { roles: Object.fromEntries(Object.entries(raw.roles).map(([k, v]) => [k, String(v)])) }
      : {}),
    ...(raw.jenkins && (raw.jenkins.job_name || (raw.jenkins.jobs && Object.keys(raw.jenkins.jobs).length > 0))
      ? {
          jenkins: {
            ...(raw.jenkins.job_name ? { jobName: raw.jenkins.job_name } : {}),
            branchParam: raw.jenkins.branch_param ?? 'oa_branch',
            defaultParams: raw.jenkins.default_params ?? {},
            ...(raw.jenkins.jobs
              ? {
                  jobs: Object.fromEntries(
                    Object.entries(raw.jenkins.jobs)
                      .filter(([, v]) => v?.job_name)
                      .map(([k, v]) => [
                        k,
                        {
                          jobName: v!.job_name as string,
                          ...(v!.branch_param ? { branchParam: v!.branch_param } : {}),
                          ...(v!.env_param ? { envParam: v!.env_param } : {}),
                          ...(v!.default_params ? { defaultParams: v!.default_params } : {}),
                        },
                      ]),
                  ),
                }
              : {}),
          },
        }
      : {}),
    ...(raw.databases
      ? { databases: Object.fromEntries(Object.entries(raw.databases).map(([k, v]) => [k, { mcp: v.mcp ?? '', ...(v.desc ? { desc: v.desc } : {}) }])) }
      : {}),
    ...(raw.test_environments
      ? { testEnvironments: Object.fromEntries(Object.entries(raw.test_environments).map(([k, v]) => [k, { url: v.url ?? '', ...(v.account ? { account: v.account } : {}), ...(v.password ? { password: v.password } : {}), ...(v.desc ? { desc: v.desc } : {}) }])) }
      : {}),
  };
}
